default: &default
 adapter: postgresql
 encoding: unicode
 database: demo_app
 pool: 50
 host: localhost
 username: postgres
 password: postgres

development:
 <<: *default
 database: demo_app

production:
 <<: *default
 database: demo_app
 username: postgres
 password: <%= ENV['FOUND_FY_DATABASE_PASSWORD'] %>
