# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3afd0cedf6c9451507502489302b7f4825cb7c5d2074b1af7906dc28ed9aed9ad6eda717f83f49cc66df2d2e28b5f6b6590f241bec1b1c0b490490b4ed365ab

test:
  secret_key_base: 266a19ba9a93aedaec236dd5f3e55f9926b8041ef49f447194c877b509cc29747cfcbf0a80933c81447c99d5762535342d62e5d06666d937f97cf2f1ecffb3c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
